# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/zzzhr/CLionProjects/fuck

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/zzzhr/CLionProjects/fuck

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zzzhr/CLionProjects/fuck/CMakeFiles /Users/zzzhr/CLionProjects/fuck/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/zzzhr/CLionProjects/fuck/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named fuck

# Build rule for target.
fuck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 fuck
.PHONY : fuck

# fast build rule for target.
fuck/fast:
	$(MAKE) -f CMakeFiles/fuck.dir/build.make CMakeFiles/fuck.dir/build
.PHONY : fuck/fast

frame/main_frame.o: frame/main_frame.cpp.o

.PHONY : frame/main_frame.o

# target to build an object file
frame/main_frame.cpp.o:
	$(MAKE) -f CMakeFiles/fuck.dir/build.make CMakeFiles/fuck.dir/frame/main_frame.cpp.o
.PHONY : frame/main_frame.cpp.o

frame/main_frame.i: frame/main_frame.cpp.i

.PHONY : frame/main_frame.i

# target to preprocess a source file
frame/main_frame.cpp.i:
	$(MAKE) -f CMakeFiles/fuck.dir/build.make CMakeFiles/fuck.dir/frame/main_frame.cpp.i
.PHONY : frame/main_frame.cpp.i

frame/main_frame.s: frame/main_frame.cpp.s

.PHONY : frame/main_frame.s

# target to generate assembly for a file
frame/main_frame.cpp.s:
	$(MAKE) -f CMakeFiles/fuck.dir/build.make CMakeFiles/fuck.dir/frame/main_frame.cpp.s
.PHONY : frame/main_frame.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/fuck.dir/build.make CMakeFiles/fuck.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/fuck.dir/build.make CMakeFiles/fuck.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/fuck.dir/build.make CMakeFiles/fuck.dir/main.cpp.s
.PHONY : main.cpp.s

model/user_model.o: model/user_model.cpp.o

.PHONY : model/user_model.o

# target to build an object file
model/user_model.cpp.o:
	$(MAKE) -f CMakeFiles/fuck.dir/build.make CMakeFiles/fuck.dir/model/user_model.cpp.o
.PHONY : model/user_model.cpp.o

model/user_model.i: model/user_model.cpp.i

.PHONY : model/user_model.i

# target to preprocess a source file
model/user_model.cpp.i:
	$(MAKE) -f CMakeFiles/fuck.dir/build.make CMakeFiles/fuck.dir/model/user_model.cpp.i
.PHONY : model/user_model.cpp.i

model/user_model.s: model/user_model.cpp.s

.PHONY : model/user_model.s

# target to generate assembly for a file
model/user_model.cpp.s:
	$(MAKE) -f CMakeFiles/fuck.dir/build.make CMakeFiles/fuck.dir/model/user_model.cpp.s
.PHONY : model/user_model.cpp.s

util/common_api.o: util/common_api.cpp.o

.PHONY : util/common_api.o

# target to build an object file
util/common_api.cpp.o:
	$(MAKE) -f CMakeFiles/fuck.dir/build.make CMakeFiles/fuck.dir/util/common_api.cpp.o
.PHONY : util/common_api.cpp.o

util/common_api.i: util/common_api.cpp.i

.PHONY : util/common_api.i

# target to preprocess a source file
util/common_api.cpp.i:
	$(MAKE) -f CMakeFiles/fuck.dir/build.make CMakeFiles/fuck.dir/util/common_api.cpp.i
.PHONY : util/common_api.cpp.i

util/common_api.s: util/common_api.cpp.s

.PHONY : util/common_api.s

# target to generate assembly for a file
util/common_api.cpp.s:
	$(MAKE) -f CMakeFiles/fuck.dir/build.make CMakeFiles/fuck.dir/util/common_api.cpp.s
.PHONY : util/common_api.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... fuck"
	@echo "... frame/main_frame.o"
	@echo "... frame/main_frame.i"
	@echo "... frame/main_frame.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... model/user_model.o"
	@echo "... model/user_model.i"
	@echo "... model/user_model.s"
	@echo "... util/common_api.o"
	@echo "... util/common_api.i"
	@echo "... util/common_api.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

